spring:
  application:
    name: jieapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.6:3306/jieapi_fronted
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 192.168.153.6
    database: 0
    password: 123456
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
server:
  port: 7529
  servlet:
    context-path: /api
#    session:
#      cookie:
#        domain: 192.168.124.8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

jieapi:
  client:
    access-key: jie
    secret-key: abcdefgh

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.153.6:8848


oss:
  enabled: true
  type: MINIO
  endpoint: http://192.168.153.6:9000
  access-key: minioadmin
  secret-key: minioadmin
  default-bucket-name: api-bucket